blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/omersia/omersia/discussions
    about: Posez des questions et discutez avec la communautÃ©
  - name: ğŸ“š Documentation
    url: https://github.com/omersia/omersia/tree/main/docs
    about: Consultez la documentation avant de poser une question